### ISSUE TITLE
The new API

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-draw#292] opened 2016-04-25 22:13 UTC
I've found it hard to transition from the old 0.4 API to the new 0.6 dito. There are a few main aspects that I believe need to be adressed:

- The <code>draw.changed</code> event is fired more or less all the time, even when no feaures are selected and I just drag the map
- The callback of the <code>draw.changed</code> event contains all features, added and about-to-be-added
- There is no way of determining in the event callbacks or via the get()/getAll() methods which features are actually added and which are about-to-be-added
- The add() method makes a dirty check on the geometry coordinates field to determine if an existing feature really has to be updated - however it disregards any changes to the properties, so to update a feature in the draw store you need to update the coordinates

**Comment by mcwhittemore** [comment] 2016-04-26 15:29
1 and 2 were just fixed in #283. 3 has been moved to #294. 4 is a dupe of #287.

Closing this issue to have these conversations on those tickets.

**Closed by mcwhittemore** 2016-04-26 15:29 UTC
