### ISSUE TITLE
Error Loading FeatureCollection using the set function

### ISSUE THREAD

**Issue by ThomasAlanParker** [mapbox/mapbox-gl-draw#611] opened 2017-03-26 17:38 UTC
Hello, I'm porting my application from using openlayers as our web mapping tool to mapbox. I'm very happy with the choice so far. But I am having trouble importing my features in to the mapbox-gl-draw tool. I get an error saying the properties member should be an object. Can someone tell me what I'm doing incorrectly? And is this the proper way to load a feature in to the drawing tool for editing?

Thanks,
Tom

        var draw = new MapboxDraw({
            displayControlsDefault: true
        });
        map.addControl(draw);

        var testfeature = {
            "type": "FeatureCollection",
            "features": [
                {
                    "type": "Feature",
                    "geometry": {
                        "type": "LineString",
                        "coordinates": [
                            [-89.3799029, 44.23992173],
                            [-89.37998873, 44.23604766],
                            [-89.37526804, 44.23589392],
                            [-89.37548262, 44.23989098],
                            [-89.37630874, 44.24201793],
                            [-89.3790124, 44.24178735],
                            [-89.37984925, 44.24164899],
                            [-89.3799029, 44.23992173]
                        ]
                    },
                    "properties": { "prop0": "value0", "prop1": 0.0 }
                }
            ]
        };

        draw.set(testfeature);

![image](https://cloud.githubusercontent.com/assets/13923274/24333598/70f06352-1220-11e7-9748-aab5fdaa6776.png)

**Comment by ThomasAlanParker** [comment] 2017-03-26 18:24
To follow up, I took the output of draw.GetAll(), coverted it to geojson and get the same error.

   var testfeature = {
            "type": "FeatureCollection",
            "features": [
                {
                    "id": "30929e857a550ccda366a7312fb40736",
                    "type": "Feature",
                    "properties": {},
                    "geometry": {
                        "coordinates": [[[-89.41781860352404, 44.341361059904614], [-89.41232543946537, 44.19188240924129], [-89.2022119140703, 44.30009575401749], [-89.25577026368307, 44.393392524155246], [-89.41781860352404, 44.341361059904614]]],
                        "type": "Polygon"
                    }
                }]
        };

        draw.set(testfeature);

**Comment by mcwhittemore** [comment] 2017-03-27 17:56
Tom,

Thanks for reporting this. I've tried to recreate locally and cannot seem to. Are you using any other libraries that might change how objects are created? If you can, please make a fiddle that demonstrates this error so we all know we're looking at the same thing.

Regards,
Matthew

**Comment by ThomasAlanParker** [comment] 2017-03-27 18:52
https://jsfiddle.net/ThomasAlanParker/42fb4x3w/

Hopefully this will help,  the fiddle doesn't throw an error, but I also don't see the drawing tool or my hoped for field.

Thanks for any help you can give me.

**Comment by mcwhittemore** [comment] 2017-03-27 19:00
Tom,

Thanks for this. It looks like there is a 404 with your fiddle. But poking around a bit, I think this error is coming from [an upstream bug](https://github.com/mapbox/geojsonhint/pull/62).

Regards,
Matthew

**Comment by ThomasAlanParker** [comment] 2017-03-27 19:16
Sorry, I need to learn JSFiddle, I tend to be a lurker, this standalone page demos the problem in firefox, chrome and IE. Thanks for you quick response. Any suggested workarounds to let my users load a simple polygon in to the draw tool to edit previous versions of the field polygon? I can manipulate it however is required to get in an out of the drawing tool.

Thanks!
Tom

[drawtext.zip](https://github.com/mapbox/mapbox-gl-draw/files/873520/drawtext.zip)

**Comment by mcwhittemore** [comment] 2017-03-27 19:26
Tom,

My best guess would be to do something like `feature.properties.constructor = Object` but I don't have IE locally, so this is just me guessing. When the upstream bug is fixed, I'll update it here, but until then I'm not sure how much more help I can be.

Regards,
Matthew

**Comment by ThomasAlanParker** [comment] 2017-03-27 19:28
Ok, well we definitely don’t need to use IE, I was just using it with the Visual Studio Javascript Debugger, we deploy on chrome, same error in all browsers for me though.

Thanks again,
Tom

**Comment by mcwhittemore** [comment] 2017-05-16 14:57
I've been unable to reproduce this. Closing until there is a fiddle that shows this bug.

**Closed by mcwhittemore** 2017-05-16 14:57 UTC
