### ISSUE TITLE
Performance of mapbox-gl-js degrades when draw is enabled

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-draw#296] opened 2016-04-26 17:07 UTC
I noticed this when reviewing/testing #295...

1. Go to http://firefly.ibk.se/~racer/drawtest/
2. Zoom the map in/out and get a feel for the current performance (which is mostly related to screen size)
3. Enable draw and do the same

My impression is that overall performance degrades quite significantly, even though no features are added to the draw sources at all. Must be some hook in draw that's stealing CPU cycles.

**Comment by averas** [comment] 2016-04-26 17:16
I can't see anything obvious related to draw in the profiler.. but the CPU impact is definitely higher.. and the performance difference is evident, again, without any data on the sources at all.

Any clues here @mourner @lucaswoj ?

**Comment by mcwhittemore** [comment] 2016-04-26 17:43
Draw uses the zoom level to render features differently. This means that on zoom we're rerendering which, even with an empty dataset, would call setData on at least one source.

**Comment by mourner** [comment] 2016-04-26 17:48
@mcwhittemore can you expand on that? What differences exactly require setData on every zoom frame?

**Comment by mcwhittemore** [comment] 2016-04-26 17:54
@mourner Draw turns LineStrings and Polygons that are too small to be seen at the current zoom level to points which are styled as circle and can be seen at every zoom level. To do this we need to evaluate the size of a feature at the current zoom level. This is done on zoom end. https://github.com/mapbox/mapbox-gl-draw/blob/master/src/events.js#L144

**Comment by mourner** [comment] 2016-04-26 18:03
@mcwhittemore empty setData on zoomend doesn't seem like it should interfere with performance in any way. Anything else that GL draw hooks up?

**Comment by mcwhittemore** [comment] 2016-04-26 18:20
All the event handlers are here.

https://github.com/mapbox/mapbox-gl-draw/blob/master/src/events.js#L131-L145

There are a bunch of them.

**Comment by mcwhittemore** [comment] 2016-04-26 18:21
Oh, most of the mouse handlers are doing `queryRenderedFeatures` requests. We can probs cache this.

**Comment by averas** [comment] 2016-04-26 18:23
.. also <code>zoomend</code> would only be called on the "end of a zoom" I hope. :-) What I currently experience is that performance it hit _during_ zooming as well.

**Comment by averas** [comment] 2016-04-26 18:28
So, it's the <code>queryRenderedFeatures</code> fired as a result of <code>mousemove</code> I guess?

**Comment by mcwhittemore** [comment] 2016-04-26 18:33
@averas that seems like a good possibility.

**Comment by averas** [comment] 2016-04-28 21:14
Okay, so I spent an hour or so trying to pin point the root cause of the performance degradation, and I actually got quite surprised when I arrived at a point where I was able to rule out any expensive calls executed by the event listeners (such as querying for features)..

I removed more and more code until draw became super-skinny.. but still.. as soon as I enabled it performance was significantly impacted. Finally I got to a point where I more or less only added the empty sources and the draw theme layers.. and as it turned out, that is enough.. I even extracted this to a completely standalone codepen and the phenomenon is present!

http://codepen.io/anon/pen/qZJprY

This obviously indicates that the bug (or simply limitation of some kind) is upstream. It may be that the styles used by draw contains some fishy filter or so, but since mapbox-gl-js doesn't complain I'd still label that a bug..

@mcwhittemore @mourner @lucaswoj

**Comment by mcwhittemore** [comment] 2016-05-06 14:58
On #303 @stepankuzmin pointed out that the perf is worse on retina displays. My guess is that this is also a upstream perf problem of gl-js, but I wanted to link the issue here for future reference.

**Comment by mcwhittemore** [comment] 2016-06-01 19:30
Perf has seen with a huge step up with 8bbb00a9fefd2d3d91cf213d9b9ac733548bed21 and mapbox-gl@0.19.

Closing this for now, though I suspect there are still a few ways we can improve the perf of draw.

**Comment by averas** [comment] 2016-06-07 23:49
On mapbox-gl-js 0.19.0 I am still experiencing a major performance impact simply by enabling draw...
(I actually perceive it being worse than with earlier versions). And this is with nothing drawn at all.

If I zoom in/out continuously with draw enabled it lags significantly and CPU is way up. Without draw enabled it's smooth and the CPU does not sky rocket.

Please verify on the updated codepen at: http://codepen.io/anon/pen/MeaXGb
(Add/remove draw layers with the buttons)

**Comment by mourner** [comment] 2016-06-08 11:04
I figured out the cause of the bad rendering performance, describing it in https://github.com/mapbox/mapbox-gl-js/issues/2510#issuecomment-224556560. tl;dr Getting rid of interleaving hot/cold sources in the style will improve performance dramatically. You would either group them as all cold + all hot, or even better, somehow refactor the distinction so that all the layers could use the same source (maybe with additional layer filters?). @mcwhittemore

**Comment by lucaswoj** [comment] 2016-06-08 13:45
I originally proposed having hot and cold sources as a perf optimization. My thinking was that `GeoJSON to vector tile processing time` was a function of the # of vertices within a source, so having the most rapidly updating features within their own source would improve perf.

> You would either group them as all cold + all hot

Let's try this first.

**Comment by mourner** [comment] 2016-06-08 14:06
@lucaswoj ah, yeah — the distinct sources to reduce setData work make sense. Let's group hot/cold as a quick stopgap then but target tile clipping optimization in GL JS in the near term.

**Comment by samanpwbb** [comment] 2016-06-08 14:39
> You would either group them as all cold + all hot

Have a fix for this coming up.

**Comment by samanpwbb** [comment] 2016-06-08 23:43
Layer grouping is done and in the latest release, seems best to leave open until the upstream fix comes through though.

**Comment by mcwhittemore** [comment] 2016-06-28 15:05
@samanpwbb I'm going to close this. We can search closed issues if we need to.

**Closed by mcwhittemore** 2016-06-28 15:05 UTC
Labels: performance, upstream

**Comment by levgaas** [comment] 2019-07-07 21:57
Bumping up on that issue since `mousemove` event takes a lot of CPU.

Spent some time debugging and found out that every mousemove event 
`currentMode.mousemove(event);` is triggered which in return triggers

```
DrawContext.store.render();
DrawContext.ui.updateMapClasses();
```

In other words every `mousemove` event I have all mapbox re-rendered. If it's disabled, everything works fine.

**Comment by usb248** [comment] 2020-03-19 12:25
Any updates ? mapbox-gl-js is so slowing. My CPU becomes crazy o_o

**Comment by bw1984** [comment] 2020-05-21 22:46
i am using the latest version and am experiencing significant performance impacts when draw is enabled even when only loading a simple triangle. has this issue resurfaced?
