### ISSUE TITLE
Marker positioning within draw feature. 

### ISSUE THREAD

**Issue by mjpbradley** [mapbox/mapbox-gl-draw#284] opened 2016-04-08 16:26 UTC
It seems that the z-index of markers cannot be controlled, causing them to be loaded after a new polygon is drawn - see below. 

Here I am handling a click event and it is causing the polygon to change mode each time. I am not sure if this is a mapbox-gl issue or separate draw issue?

![image](https://cloud.githubusercontent.com/assets/17411907/14390418/c156a96e-fdae-11e5-9c15-e58b7e5f6ab2.png)

**Comment by mjpbradley** [comment] 2016-04-08 16:27
Running mapbox-gl-draw@v0.4.0

**Comment by mcwhittemore** [comment] 2016-04-08 16:54
Draw works as an overlay on your style so this bug is 'by design' :(. That said, I'd like to understand this a bit more to see how/if Draw could make this easier.

- How did this the polygon on the map? Did I draw it or was it added via Draw.add? Are both of these options possible.
- Why am I clicking on 'civic center plaza'?

**Comment by mjpbradley** [comment] 2016-04-13 16:18
The polygon is drawn by the user. 
The marker is actually added once the polygon has been drawn, with a attached popup when clicked. So here by clicking the _added_ marker which is sitting below the drawn polygon, is triggering the polygon selection.

**Comment by mcwhittemore** [comment] 2016-04-14 06:29
@mjpbradley do you want to be able to edit the polygon again or is this polygon in a finished state.

If it is in a finished state, I'd move the polygon out of draw and into your own geojson source.

If not than I have a few ideas about how we might be able to help support this kind of thing, but they would be out of my working capacity for a few months at least. I can outline them if you want to implement them, but we should only go down this route if moving the data out of draw is not an option in anyway.

**Comment by mjpbradley** [comment] 2016-04-19 12:58
It needs to be constantly editable. 

However moving it out of draw and into a geojson seems to work better, i.e. moving it in and out of draw every time it needs to be edited.
Although handling the the editing state, it a bit tricky in that you have to click it twice to start a redraw (once to select drawing and again to edit feature inside Draw)

**Comment by mcwhittemore** [comment] 2016-05-06 15:08
This is a good use cause for a custom mode. Closing in favor of #289 as a more holistic solution to the 'I need a type of interaction that draw doesn't support' problem.

**Closed by mcwhittemore** 2016-05-06 15:08 UTC
