### ISSUE TITLE
Dragging point with type: 'symbol' layer makes the point flicker

### ISSUE THREAD

**Issue by amagee** [mapbox/mapbox-gl-draw#768] opened 2018-04-27 06:19 UTC
**mapbox-gl-js version**: 0.44.2
**mapbox-gl-draw version**: 1.0.7

I'm not sure if I'm observing a mapbox-gl-draw issue or if I'm just doing something silly, but I want to make some draggable points that are rendered as icons. 

I've done this by taking the default theme from `@mapbox/mapbox-gl-draw/src/lib/theme.js` and modifying the `gl-draw-point-inactive`, `gl-draw-point-active` and `gl-draw-point-stroke-active` styles, then passing the modified theme to the MapboxDraw object.

But when I drag the icon, it constantly flickers in and out of existence.

Demo: https://jsbin.com/hidevekoda/edit?html,output

Steps to trigger behaviour:

1. Drag the airplane around the map.

### Expected Behavior:

Plane should move smoothly.

### Actual Behavior

Plane flickers in and out of existence.

**Comment by amagee** [comment] 2018-04-29 23:59
I found I can avoid the problem by adding `"icon-allow-overlap": true` and `"icon-ignore-placement": true` to the style's `layout` property of the symbol style. 

Ie. in the jsbin above, amending the `airplane` function to

```
  function airplane(style) {
    return {
      id: style.id,
      filter: style.filter,
      type: 'symbol',
      layout: {
        'icon-image': 'airfield-11',
        'icon-allow-overlap": true,
        'icon-ignore-placement": true
      }
    };
  }
```

**Comment by amagee** [comment] 2018-10-22 05:11
Note that as of Mapbox 0.49.0, in addition to the above, `text-allow-overlap` and `text-ignore-placement` are required for features with text fields.

**Comment by p-fischer** [comment] 2019-03-26 09:12
Thanks @amagee for documenting your problem & solution here. It helped me with my problem.

While using the mapbox android SDK I had the same issue with draggable symbols.
The problem was resolved by setting `symbolManager.iconAllowOverlap = true`.
However, I think this is just a workaround (which might not be approachable in every situation). So I hope for the issue to be fixed.

**Comment by kkaefer** [comment] 2020-01-07 16:04
Yes, this behaves as intended and setting `icon-allow-overlap` and optionally `icon-ignore-placement` gives you the desired effect.

**Closed by kkaefer** 2020-01-07 16:04 UTC
